INSERT INTO userInfo
        (customer_id,
         first_name,
         last_name,
         sex,
         birthday,
         address,
         email,
         phone,
         regist_user,
         regist_time,
         update_user,
         update_time,
         delete_flag)
VALUES (:customer_id,
        :firstName,
        :lastName,
        :sex,
        :birthday,
        :address,
        :email,
        :phone,
        :registUser,
        :registTime,
        :updateUser,
        :updateTime,
        :deleteFlag);